version: "3.3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_SECRET: sajal48
    networks:
      - mysql_mysql-phpmyadmin

networks:
  mysql_mysql-phpmyadmin:
    external: true