version: "3.3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host
      DB_PORT: port
      DB_USER: user
      DB_SECRET: secret
    networks:
      - mysql_mysql-phpmyadmin

networks:
  mysql_mysql-phpmyadmin:
    external: true